@echo off
echo Starting Flutter Web Development Server...
echo Cleaning previous build...
flutter clean
echo Getting dependencies...
flutter pub get
echo Building for web...
flutter run -d chrome --web-renderer html --dart-define=FLUTTER_WEB_USE_SKIA=false
pause
